version: "3.1"

services:
  opencart:
    build:
      context: docker
      dockerfile: Dockerfile.dev
      args:
        OPENCART_VERSION:
        APP_PORT:
        OPENCART_PATH:
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:${WOOVI_EXTENSION_PATH}
      - opencart:${OPENCART_PATH}

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  opencart:
